apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incidents
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chazapp/hello-api
    targetRevision: HEAD
    path: ./k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: hello
  syncPolicy:
    automated: {}
